# Generated by Django 6.0.3 on 2026-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_check_in_time_booking_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('advance_paid', 'Advance Paid'), ('full_paid', 'Full Paid')], default='advance_paid', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
