# Generated by Django 6.0.3 on 2026-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
