# Generated by Django 6.0.3 on 2026-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ownerprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
