# Generated by Django 6.0.3 on 2026-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
