# Generated by Django 6.0.3 on 2026-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_brokerprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='id_proof',
            field=models.FileField(upload_to='broker_ids/'),
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='license_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='profile_image',
            field=models.ImageField(upload_to='brokers/'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='id_proof',
            field=models.FileField(upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='profile_image',
            field=models.ImageField(upload_to='owners/'),
        ),
    ]
