# Generated by Django 6.0.3 on 2026-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_travelerprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
