# Generated by Django 6.0.3 on 2026-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0004_travelerprofile_occupation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
