"""
Django settings for staylinkproject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import mimetypes
from datetime import timedelta
import os
from dotenv import load_dotenv
from celery.schedules import crontab
load_dotenv()


# Ensure correct MIME types so CSS/JS aren't blocked
mimetypes.add_type('text/css', '.css', True)
mimetypes.add_type('text/css', '.css', False)
mimetypes.add_type('application/javascript', '.js', True)
mimetypes.add_type('application/javascript', '.js', False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "django",
    "0.0.0.0",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',                          
    'chat',
    'accounts',
    'django_celery_beat',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist', 
    'drf_spectacular', 
    'owner',
    'traveler',
    'bookings',
    'payments',
    'broker',
    'notifications',
    'admin_panel',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'staylinkproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                            'django.template.context_processors.static',
],
        },
    },
]

WSGI_APPLICATION = 'staylinkproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}



SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),

    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,

    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),

    # 
    "UPDATE_LAST_LOGIN": True,
}


AUTH_USER_MODEL = 'accounts.CustomUser'

CORS_ALLOW_ALL_ORIGINS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



SPECTACULAR_SETTINGS = {
    'TITLE': 'StayLink API',
    'DESCRIPTION': 'API documentation for StayLink platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}




GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
FRONTEND_URL = os.getenv("FRONTEND_URL")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD"
)




# ============================================
# CELERY CONFIGURATION
# ============================================

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/0"
)

CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    "redis://127.0.0.1:6379/1"
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"

# Hard kill a task after 30 minutes
CELERY_TASK_TIME_LIMIT = 30 * 60

# Soft warning raised at 25 minutes inside the task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60

# Restart worker process after 200 tasks — prevents memory leaks
# Important on Windows with --pool=solo
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200

# Show task state as STARTED while running
CELERY_TASK_TRACK_STARTED = True

# All accounts app tasks go to email_queue
# Later you'll add booking_queue, notification_queue here
CELERY_TASK_ROUTES = {
    "accounts.tasks.*": {"queue": "email_queue"},
    "bookings.tasks.*": {"queue": "email_queue"},
}



RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")


# settings.py — ONE place for ALL scheduled tasks
CELERY_BEAT_SCHEDULE = {

    # ── OTP CLEANUP ──────────────────────────────────────
    # Runs every 15 minutes
    # Deletes expired EmailVerification rows
    "cleanup-expired-otps": {
        "task": "accounts.tasks.cleanup_expired_otps_task",
        "schedule": crontab(minute="*/15"),
    },

    # ── BOOKING REMINDERS ─────────────────────────────────
    # Runs daily at 9:00 AM IST
    # Sends reminder to travelers with check-in in 7 days
    "one-week-reminders": {
        "task": "bookings.tasks.send_one_week_reminders",
        "schedule": crontab(hour=9, minute=0),
    },

    # Runs daily at 9:05 AM IST
    # Sends reminder to travelers with check-in in 2 days
    "two-day-reminders": {
        "task": "bookings.tasks.send_two_day_reminders",
        "schedule": crontab(hour=9, minute=5),
    },

    # Runs every 30 minutes
    # Sends reminder to travelers checking in within 2 hours
    "two-hour-reminders": {
        "task": "bookings.tasks.send_two_hour_reminders",
        "schedule": crontab(minute="*/30"),
    },
}


# ============================================
# DJANGO CHANNELS (WebSocket) CONFIGURATION
# ============================================

# This tells Django to use Channels ASGI app
# instead of the normal WSGI app for handling requests
ASGI_APPLICATION = 'staylinkproject.asgi.application'

# Channel layers use Redis as a message broker
# between WebSocket connections.
# Same Redis instance that Celery already uses.
REDIS_HOST = os.getenv(
    "REDIS_HOST",
    "127.0.0.1"
)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    REDIS_HOST,
                    6379
                )
            ],
        },
    },
}