# Generated by Django 6.0.3 on 2026-06-19 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerconnection',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokerreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='BrokerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_rejected', 'Connection Rejected'), ('new_review', 'New Review'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerUnlistedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('room', 'Room'), ('hostel', 'Hostel'), ('pg', 'PG'), ('commercial', 'Commercial'), ('land', 'Land'), ('house', 'House')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.CharField(choices=[('night', 'Per Night'), ('day', 'Per Day'), ('month', 'Per Month'), ('year', 'Per Year')], default='month', max_length=10)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=15)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Broker commission percentage per booking', max_digits=5)),
                ('private_notes', models.TextField(blank=True, help_text='Private notes visible only to broker')),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True, help_text='Set to false if property is no longer available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlisted_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('booking', 'Booking'), ('commission', 'Commission'), ('followup', 'Follow Up'), ('client', 'Client Info'), ('property', 'Property')], default='general', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_notes', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='broker.brokerunlistedproperty')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerBookingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=15)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_booking_records', to=settings.AUTH_USER_MODEL)),
                ('unlisted_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_records', to='broker.brokerunlistedproperty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
