# Generated by Django 6.0.3 on 2026-05-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='admin_feedback',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
