# Generated by Django 6.0.3 on 2026-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_property_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='management_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='management_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='management_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
