# Generated by Django 6.0.3 on 2026-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_property_management_email_property_management_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='max_guest',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='privacy_level',
            field=models.IntegerField(help_text='1 to 5'),
        ),
    ]
