# Generated by Django 6.0.3 on 2026-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_propertyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ambience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
