# Generated by Django 6.0.3 on 2026-05-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_remove_propertyavailability_is_manual_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingRequest',
        ),
    ]
